Newspaper:
  The Globe and Mail:
    WOEID: 23424775
    rss:
      - http://www.theglobeandmail.com/news/?service=rss
  The National Post:
    WOEID: 4118
    rss:
      -
  The Record:
    WOEID: 23396898
    rss:
      - http://www.therecord.com/feeds?types=article&query=fullcategory:/news&FilterQueries=category:therecord&orderby=releasetimestamp+desc
#  Toronto Sun:
#    WOEID: 4118
#    rss:
#      - http://www.torontosun.com/home/rss.xml
#      - http://www.torontosun.com/news/world/rss.xml
#      - http://www.torontosun.com/news/canada/rss.xml

Online:
  Google News:
    WOEID: 4118
    rss:
      - https://news.google.ca/news/feeds?q=%22amnesty+international%22&hgl=ca&pz=1&cf=all&ned=ca&hl=en&topic=n&output=rss
  CBC:
    WOEID: 4118
    rss:
      - http://rss.cbc.ca/lineup/topstories.xml
      - http://rss.cbc.ca/lineup/world.xml
      - http://rss.cbc.ca/lineup/canada.xml
      - http://rss.cbc.ca/lineup/politics.xml
  Canada.com:
    WOEID: 4118
    rss:
      -
  MacLeans:
    WOEID: 4118
    rss:
      -
