Newspaper:
  The Globe and Mail:
    WOEID: 23424775
    rss:
      - http://www.theglobeandmail.com/news/?service=rss
  The National Post:
    WOEID: 4118
    rss:
      -
  The Record:
    WOEID: 23396898
    rss:
      - http://www.therecord.com/feeds?types=article&query=fullcategory:/news&FilterQueries=category:therecord&orderby=releasetimestamp+desc
#  Toronto Sun:
#    WOEID: 4118
#    rss:
#      - http://www.torontosun.com/home/rss.xml
#      - http://www.torontosun.com/news/world/rss.xml
#      - http://www.torontosun.com/news/canada/rss.xml

Online:
  Google News:
    WOEID: 4118
    rss:
      - https://news.google.ca/news/feeds?q=%22amnesty+international%22&hgl=ca&pz=1&cf=all&ned=ca&hl=en&topic=n&output=rss
  CBC:
    WOEID: 4118
    rss:
      - http://rss.cbc.ca/lineup/topstories.xml
      - http://rss.cbc.ca/lineup/world.xml
      - http://rss.cbc.ca/lineup/canada.xml
      - http://rss.cbc.ca/lineup/politics.xml
  Canada.com:
    WOEID: 4118
    rss:
      -
  MacLeans:
    WOEID: 4118
    rss:
      -
  Rabble: # http://rabble.ca/
    WOEID: 4118
    rss:
      - 
  Sun: # http://www.sunnewsnetwork.ca/
    WOIED: 4118
    rss:
      -
  CTVNews: # http://www.ctvnews.ca/
    WOIED: 4118
    rss:
      -
      
# Others to investigate
# Non-Canadian news organizations that report on Canada:
# NY Times http://topics.nytimes.com/top/news/international/countriesandterritories/canada/index.html
# Guardian http://www.guardian.co.uk/world/canada?INTCMP=SRCH
# BBC http://www.bbc.com/news/world/us_and_canada/
# The Economist http://www.economist.com/topics/canada
# Foreign Policy http://www.foreignpolicy.com/category/topic/canada
# FP, see also http://blog.foreignpolicy.com/category/topic/human_rights

# General Interest National Magazines
# The Walrus http://thewalrus.ca/
# The Dominion http://www.dominionpaper.ca/
# Maisonneuve http://www.maisonneuve.org/

# Special Interest Magazines
# Diplomat and International http://diplomatonline.com/mag/
