Settings:
  result_type: recent
  returns_per_page: 100
# result_type example values;
# * mixed: include both popular and real time results in the response.
# * recent: return only the most recent results in the response
# * popular: return only the most popular results in the response.

Regions:
# These are the largest 14 cities in Canada
  GTA:
    area:
      -  
        lat: 43.7
        long: -79.416
        range: 40km
  Montreal:
    area:
      -  
        lat: 45.509
        long: -73.588
        range: 40km
  Vancouver:
    area:
      -  
        lat: 49.25
        long: -123.119
        range: 20km
    comment: Vancouver is close to the border so it has a smaller range
  Calgary:
    area:
      -  
        lat: 51.05
        long: -114.085
        range: 40km
  Ottawa:
    area:
      -  
        lat: 45.411
        long: -75.698
        range: 40km
  Edmonton:
    area:
      -  
        lat: 53.55
        long: -113.469
        range: 40km
  Winnipeg:
    area:
      -  
        lat: 49.884
        long: -97.147
        range: 40km
  Quebec City:
    area:
      -  
        lat: 46.812
        long: -71.215
        range: 40km
  Halifax:
    area:
      -  
        lat: 44.647
        long: -63.574
        range: 40km
  Kitchener:
    area:
      -  
        lat: 43.45
        long: -80.483
        range: 40km
  London:
    area:
      -  
        lat: 42.984
        long: -81.250
        range: 20km
  Victoria:
    area:
      -  
        lat: 48.422
        long: -123.366
        range: 20km
  St Catharines:
    area:
      -  
        lat: 43.183
        long: -79.233
        range: 10km
    comment: St Catharines is very close to the border so it has a smaller range
  Oshawa:
    area:
      -  
        lat: 43.9
        long: -78.85
        range: 5km

SearchTerms:
# Note: 'amnesty.org' will also return results for 'amnesty.org.au' and 'amnesty.org.uk'
  - 'Amnesty International'
  - 'AmnestyInternational'
  - 'amnesty.ca'
  - 'amnesty.org'
  - 'amnestyusa.org'
  - 'aiusa.org'
  - '@aicanadamedia'
  - '@AmnestySecurity'
  - '@AmnestyNow'
  - '@LGBT_Amnesty'
  - '@AmnistieCA'
  - '@AICanadaBHR'
  - '@AI_WomenRights'
  - '@AmnestyToronto'
  - '@AlexNeveAmnesty'
# Topics
  - '#humanrights'
  - '#deathpenalty'
# Current events
# Turkey
  - '#occupygezi'
  - '#direngezipark'
  - '#Taksim'
# POC
  - '#FreeNasrinSotoudeh'
  - '#Guantanamo'

ActivityZone:
# These are hotspots around the world, protests, rallies etc. A hotspot consists of an array circles
# Turkey protests in Gezi
  Gezi:
    startdate: '2013-06-01'
    enddate: '2013-06-30'
    area:
      -  
        lat: 41.038333
        long: 28.986944
        range: 0.5km
# Toronto Pride March
#  TorontoPride:
#    startdate: '2013-06-21'
#    enddate: '2013-06-30'
#    area:
#      -  
#        lat: 43.669672
#        long: -79.384957
#        range: 0.3km
#      -  
#        lat: 43.667173
#        long: -79.385086
#        range: 0.2km
#      -  
#        lat: 43.66618
#        long: -79.383498
#        range: 0.3km

IgnoredWords:
# Note: Ignored words should be in lower case
  - ''
  - '&amp'
  - 'and'
  - 'rt'
  - 'of'
  - 'to'
  - 'the'
  - 'in'
  - 'on'
  - 'a'
  - 'is'
  - 'at'
  - 'be'
  - 'you'
  - 'it'
  - 'our'
  - 'this'
  - 'that'
  - 'from'
  - 'about'
  - 'by'
  - 'must'
  - 'as'
  - 'has'
  - 'us'
  - 'what'
  - 'have'
  - 'not'
  - 'for'
  - 'are'
  - 'its'
  - 'an'
